using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//Did not know this just includes the top-level System namespace and no other subdirectories in the namespace, much cleaner than C++
using System;
//By extension, this includes specifically the Linq namespace (accessed through the System namespace)
using System.Linq;
using Random = UnityEngine.Random;
using static RatStats;
using static UnityEngine.Rendering.DebugUI;
using UnityEngine.Events;

public class GameManager : MonoBehaviour
{
    [SerializeField]
    private GameObject theRat;

    private PlayerMovement ratMov;

    private SensoryManager sens;

    private int contaminationLevel = 0;

    private bool winRunning = false;

    public RatStats ratStats;
    [Tooltip("Drag the generated library asset here, attempts to load from runtime resources otherwise")]
    public MutationLibrary mutationLibrary;
    public List<GameObject> mutationPool { get; private set; }
    public static GameManager Instance { get; private set; }
    public UnityEvent aiUpdate;

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        if (mutationLibrary == null)
        {
            //If grabbing the library from resources, it MUST already be generated by clicking the MutationLibraryGenerator's refresh button in editor at least once
            mutationLibrary = Resources.Load<MutationLibrary>("MutationLibrary");
            mutationPool = mutationLibrary.mutationPrefabs;
        }

        ContaminationManager.Instance.thresholdPassed += OnThresholdTrigger;
        //UIManager.Instance.updateParams += OnParamUIUpdate;

        sens = gameObject.GetComponent<SensoryManager>();
        if (sens == null)
        {
            Debug.Log("SensoryManager not added to Managers List prefab!");
        }


    }
    public void SelfDestroy()
    {
        Instance = null;
        Destroy(gameObject);
    }

    public void onPlayerDead()
    {
        //more thngs to do when player dies
        UIManager.Instance.TriggerDeathEffect();
    }

    //Register the player (rat) and its accompanying (rat) stats
    public void RegisterPlayer(GameObject rat)
    {
        theRat = rat;
        ratStats = rat.GetComponent<RatStats>();
        ratMov = rat.GetComponent<PlayerMovement>();
        
        if (ratStats == null)
        {
            Debug.Log("RatStats not added to Player prefab!");
        }
        if (ratMov == null)
        {
            Debug.Log("PlayerMovement not added to Player prefab!");
        }

        ratStats.hunger = 1;
        ratStats.stamina = 1;
        ratStats.currentHungerLevel = hungerLevel.Full;
        ratStats.staminaCap = 1f;
        ratStats.mutationLevel = 0;
        ratStats.soundMultiplier = 1;

        sens.changeSmellRadius(ratStats.scentRange);
    }

    public void OnThresholdTrigger(float threshold, bool winCon)
    {
        Debug.Log("Threshold " + threshold + "% reached.");
        contaminationLevel++;

        aiUpdate.Invoke();
        //Subject to change, might want to trigger these only at certain thresholds
        //Potentially requires extra data added to ContaminationSettings to specify this
        SetpieceManager.Instance.TriggerSetpiece();

        //Handle mutation and potential environment updates from here
        if (winCon && !winRunning)
        {
            StartCoroutine(winTheGame());
        }
    }

    public IEnumerator winTheGame()
    {
        winRunning = true;
        //Time.timeScale = 0.0f;
        //Cursor.lockState = CursorLockMode.Confined;
        //Cursor.visible = true;
        yield return new WaitForSeconds(5f);
        UIManager.Instance.cueWinUI();
        StartCoroutine(GameObject.Find("RELOADQUIT").GetComponent<UIManagerTWOOOOO>().winCaseQuitToMenu(4f));
    }
   
    public void RandomMutate()
    {
        string randomMutationName = mutationPool[Random.Range(0, mutationPool.Count)].name;
        AddMutation(randomMutationName);
    }
    //Handler so mutations can be added by an identifier instead of the direct type
    public void AddMutation(string mutationName)
    {
        var prefab = mutationPool.FirstOrDefault(p => p.name == mutationName);

        if (prefab != null)
        {
            IMutation mutationComponent = prefab.GetComponent<IMutation>();

            if (mutationComponent != null)
            {
                AddMutation(mutationComponent.GetType());
            }
        }
    }

    //Called after a mutation identifier is converted into a runtime type
    //Functionally the same as the generic version if also passed a known type but still resolves at runtime (more overhead)
    //Flexible, not type-safe
    public void AddMutation(Type mutationType)
    {
        IMutation existingMutation = (IMutation)theRat.GetComponent(mutationType);

        if (existingMutation != null)
        {
            existingMutation.stackMutation();
        }
        else
        {
            IMutation newMutation = (IMutation)theRat.AddComponent(mutationType);
            newMutation.Initialize();
            newMutation.onMutate();
        }
        //Might make this an event to invoke later if multiple sources need to refresh values copied from RatStats
        ratMov.RefreshStats();
    }

    //Generic method to directly add a mutation when the type is already known at compile-time
    //Performant, type-safe
    public void AddMutation<T>() where T: Component, IMutation
    {
        T existingMutation = theRat.GetComponent<T>();

        if (existingMutation != null)
        {
            existingMutation.stackMutation();
        }
        else
        {
            T newMutation = theRat.AddComponent<T>();
            newMutation.Initialize();
            newMutation.onMutate();
        }
        ratMov.RefreshStats();
    }

    public void onJumpStackChange(int newVal)
    {
        JumpMutation newMutation = theRat.GetComponent<JumpMutation>();
        if (newMutation != null)
        {
            newMutation.SetStacks(newVal);
            ratMov.RefreshStats();
        }
        else
        {
            newMutation = theRat.AddComponent<JumpMutation>();
            newMutation.Initialize();
            newMutation.SetStacks(newVal);
        }
    }
    public void onSpeedStackChange(int newVal)
    {
        SpeedMutation newMutation = theRat.GetComponent<SpeedMutation>();
        if (newMutation != null)
        {
            newMutation.SetStacks(newVal);
            ratMov.RefreshStats();
        }
        else
        {
            newMutation = theRat.AddComponent<SpeedMutation>();
            newMutation.Initialize();
            newMutation.SetStacks(newVal);
        }
    }

    public void onClimbToggle(bool newVal)
    {
        ClimbMutation newMutation = theRat.GetComponent<ClimbMutation>();
        if (newMutation != null)
        {
            newMutation.setCurrentFlag(newVal);
        }
        else
        {
            newMutation = theRat.AddComponent<ClimbMutation>();
            newMutation.Initialize();
            newMutation.setCurrentFlag(newVal);
        }
    }

    public void changeHunger(float _change)
    {
        float scaledChange = _change * MutationUtils.ApplyStackedMultiplier(contaminationLevel, 1f, 2f, 3f);

        UIManager.Instance.changeHungerBar(scaledChange);
        ratStats.hunger += scaledChange;

        float _value = Mathf.Clamp01(ratStats.hunger);
        int index = Mathf.FloorToInt(_value * 5f);
        hungerLevel previousHungerLevel = ratStats.currentHungerLevel;
        switch (index)
        {
            case 0: 
                ratStats.currentHungerLevel = hungerLevel.Ravenous;
                ratStats.staminaCap = 0.4f;
                break;
            case 1: 
                ratStats.currentHungerLevel = hungerLevel.Starving;
                ratStats.staminaCap = 0.5f;

                break;
            case 2: 
                ratStats.currentHungerLevel = hungerLevel.Hungry;
                ratStats.staminaCap = 0.65f;

                break;
            case 3: 
                ratStats.currentHungerLevel = hungerLevel.Peckish;
                ratStats.staminaCap = 0.8f;

                break;  
            case 4: 
                ratStats.currentHungerLevel = hungerLevel.Content;
                ratStats.staminaCap = 1f;

                break;
            case 5: 
                ratStats.currentHungerLevel = hungerLevel.Full;
                ratStats.staminaCap = 1f;
                break;
        }
        
        if (ratStats.currentHungerLevel != previousHungerLevel)
        {
            ratMov.RefreshStats();
            ratMov.AdjustStatsToHunger();
        }

        changeStamina(0);

        if (ratStats.hunger <= -0.002)
        {

            Destroy(GameObject.FindWithTag("player").gameObject);
            onPlayerDead();
            StartCoroutine(GameObject.Find("RELOADQUIT").GetComponent<UIManagerTWOOOOO>().startReload(3f));

            UIManager.Instance.cueDeathUI(2);
            //AudioManager.Instance.playDeath();
        }

    }

    public void changeStamina(float _change)
    {
        ratStats.stamina += _change;
        ratStats.stamina = Mathf.Clamp(ratStats.stamina, 0f, ratStats.staminaCap);
        UIManager.Instance.changeStaminaBar(ratStats.stamina);
    }

    public void changeScentRange(float _change)
    {
        ratStats.scentRange += _change;
        if (ratStats.scentRange < 0f)
        {
            ratStats.scentRange = 0f;
        }
    }

    public void addListener(SenseOfHearing listener)
    {
        if (sens != null)
        {
            sens.addToListeners(listener);
        }
    }

    public void removeListener(SenseOfHearing listener)
    {
        if (sens != null)
        {
            sens.removeFromListeners(listener);
        }
    }

    public void emitSound(GameObject source, Vector3 location, float intensity)
    {
        if (sens != null)
        {
            //Debug.Log("Game Manager emit sound");
            sens.emitSound(source, location, intensity);
        }
    }

}
