using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//Did not know this just includes the top-level System namespace and no other subdirectories in the namespace, much cleaner than C++
using System;
//By extension, this includes specifically the Linq namespace (accessed through the System namespace)
using System.Linq;

public class GameManager : MonoBehaviour
{
    [SerializeField]
    private GameObject theRat;

    public RatStats ratStats;
    [Tooltip("Drag the generated library asset here, attempts to load from runtime resources otherwise")]
    public MutationLibrary mutationLibrary;
    public static GameManager Instance { get; private set; }

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        if (mutationLibrary == null)
        {
            //If grabbing the library from resources, it MUST already be generated by clicking the MutationLibraryGenerator's refresh button in editor at least once
            mutationLibrary = Resources.Load<MutationLibrary>("MutationLibrary");
        }
        ContaminationManager.Instance.thresholdPassed += OnThresholdTrigger;
        UIManager.Instance.updateParams += OnParamUpdate;
    }

    public void onPlayerTrapped()
    {
        //more thngs to do when player dies
        UIManager.Instance.TriggerDeathEffect();
    }

    //Register the player (rat) and its accompanying (rat) stats
    public void RegisterPlayer(GameObject rat)
    {
        theRat = rat;
        ratStats = rat.GetComponent<RatStats>();
        if (ratStats == null)
        {
            Debug.Log("RatStats not added to Player prefab!");
        }
    }

    public void OnThresholdTrigger(float threshold)
    {
        Debug.Log("Threshold " + threshold + "% reached.");
        //Handle mutation and potential environment updates from here
    }

    public void OnParamUpdate(List<int> parameterIDs)
    {
        foreach (int id in parameterIDs)
        {
           var value =  UIManager.Instance.getParamValue(id);
           //grab the label, pass to AddMutation
        }
    }

    //Handler so mutations can be added by an identifier instead of the direct type
    public void AddMutation(string mutationName)
    {
        var prefab = mutationLibrary.mutationPrefabs.FirstOrDefault(p => p.name == mutationName);

        if (prefab != null)
        {
            IMutation mutationComponent = prefab.GetComponent<IMutation>();

            if (mutationComponent != null)
            {
                AddMutation(mutationComponent.GetType());
            }
        }
    }

    //Called after a mutation identifier is converted into a runtime type
    //Functionally the same as the generic version if also passed a known time but still resolves at runtime (more overhead)
    //Flexible, not type-safe
    public void AddMutation(Type mutationType)
    {
        IMutation existingMutation = (IMutation)theRat.GetComponent(mutationType);

        if (existingMutation != null)
        {
            existingMutation.stackMutation();
        }
        else
        {
            IMutation newMutation = (IMutation)theRat.AddComponent(mutationType);
            newMutation.Initialize();
            newMutation.onMutate();
        }
    }

    //Generic method to directly add a mutation when the type is already known at compile-time
    //Performant, type-safe
    public void AddMutation<T>() where T: Component, IMutation
    {
        T existingMutation = theRat.GetComponent<T>();

        if (existingMutation != null)
        {
            existingMutation.stackMutation();
        }
        else
        {
            T newMutation = theRat.AddComponent<T>();
            newMutation.Initialize();
            newMutation.onMutate();
        }
    }


}
