using System.Collections;
using System.Collections.Generic;
using UnityEngine;
//Did not know this just includes the top-level System namespace and no other subdirectories in the namespace, much cleaner than C++
using System;
//By extension, this includes specifically the Linq namespace (accessed through the System namespace)
using System.Linq;

public class GameManager : MonoBehaviour
{
    [SerializeField]
    private GameObject theRat;

    private PlayerMovement ratMov;

    public RatStats ratStats;
    [Tooltip("Drag the generated library asset here, attempts to load from runtime resources otherwise")]
    public MutationLibrary mutationLibrary;
    public static GameManager Instance { get; private set; }

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        if (mutationLibrary == null)
        {
            //If grabbing the library from resources, it MUST already be generated by clicking the MutationLibraryGenerator's refresh button in editor at least once
            mutationLibrary = Resources.Load<MutationLibrary>("MutationLibrary");
        }
        ContaminationManager.Instance.thresholdPassed += OnThresholdTrigger;
        UIManager.Instance.updateParams += OnParamUIUpdate;
    }

    public void onPlayerTrapped()
    {
        //more thngs to do when player dies
        UIManager.Instance.TriggerDeathEffect();
    }

    //Register the player (rat) and its accompanying (rat) stats
    public void RegisterPlayer(GameObject rat)
    {
        theRat = rat;
        ratStats = rat.GetComponent<RatStats>();
        ratMov = rat.GetComponent<PlayerMovement>();
        if (ratStats == null)
        {
            Debug.Log("RatStats not added to Player prefab!");
        }
        if (ratMov == null)
        {
            Debug.Log("PlayerMovement not added to Player prefab!");
        }
    }

    public void OnThresholdTrigger(float threshold)
    {
        Debug.Log("Threshold " + threshold + "% reached.");
        //Handle mutation and potential environment updates from here
    }

    public void OnParamUIUpdate(List<int> parameterIDs)
    {
        foreach (int id in parameterIDs)
        {
           var value = UIManager.Instance.getParamValue(id);
           string mutationName = UIManager.Instance.getParamName(id) + "Mutation";
           Component mutationComponent = theRat.GetComponent(mutationName);
           if (value is bool boolVal)
           {
                //Add the Physical Mutation
                if (boolVal && mutationComponent == null)
                {
                    AddMutation(mutationName);
                }
                else if (!boolVal)
                {
                    //Toggle the mutation off
                    if (mutationComponent != null)
                    {
                        IToggleable physMutation = mutationComponent as IToggleable;
                        physMutation.setCurrentFlag(boolVal);
                        ratMov.RefreshStats();
                    }
                }
                //Nothing if the flag is the same as parameter value
                else
                {
                    return;
                }
           }
           else if (value is int intVal)
           {
                //Update the Meta Mutation stacks
                if (mutationComponent != null)
                {
                    IStackable metaMutation = mutationComponent as IStackable;
                    metaMutation.SetStacks(intVal);
                    ratMov.RefreshStats();
                }
                else
                {
                    //Nothing if non-positive stacks are set for a mutation that's not yet added
                    if (intVal <= 0)
                    {
                        return;
                    }
                    //First add the mutation component then set any stacks if there's more than one
                    AddMutation(mutationName);
                    if (intVal > 1)
                    {
                        mutationComponent = theRat.GetComponent(mutationName);
                        IStackable metaMutation = mutationComponent as IStackable;
                        metaMutation.SetStacks(intVal);
                        ratMov.RefreshStats();
                    }
                }
           }
           
        }
    }

    //Handler so mutations can be added by an identifier instead of the direct type
    public void AddMutation(string mutationName)
    {
        var prefab = mutationLibrary.mutationPrefabs.FirstOrDefault(p => p.name == mutationName);

        if (prefab != null)
        {
            IMutation mutationComponent = prefab.GetComponent<IMutation>();

            if (mutationComponent != null)
            {
                AddMutation(mutationComponent.GetType());
            }
        }
    }

    //Called after a mutation identifier is converted into a runtime type
    //Functionally the same as the generic version if also passed a known time but still resolves at runtime (more overhead)
    //Flexible, not type-safe
    public void AddMutation(Type mutationType)
    {
        IMutation existingMutation = (IMutation)theRat.GetComponent(mutationType);

        if (existingMutation != null)
        {
            existingMutation.stackMutation();
        }
        else
        {
            IMutation newMutation = (IMutation)theRat.AddComponent(mutationType);
            newMutation.Initialize();
            newMutation.onMutate();
        }
        //Might make this an event to invoke later if multiple sources need to refresh values copied from RatStats
        ratMov.RefreshStats();
    }

    //Generic method to directly add a mutation when the type is already known at compile-time
    //Performant, type-safe
    public void AddMutation<T>() where T: Component, IMutation
    {
        T existingMutation = theRat.GetComponent<T>();

        if (existingMutation != null)
        {
            existingMutation.stackMutation();
        }
        else
        {
            T newMutation = theRat.AddComponent<T>();
            newMutation.Initialize();
            newMutation.onMutate();
        }
        ratMov.RefreshStats();
    }


}
